// imports
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Typewriter from 'typewriter-effect';

// images
import Image from 'next/image';
import p2 from '../public/p2.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import tsIcon from '../public/Typescript_icon.png';
import reactIcon from '../public/React.png';
import jsIcon from '../public/js.png';
import nextIcon from '../public/next_js.png';
import expressIcon from '../public/express_js.png';
import cssIcon from '../public/css-3.png';
import htmlIcon from '../public/html-5.png';
import prismaIcon from '../public/prisma.png';
import materialIcon from '../public/material-ui.png';
import tailwindIcon from '../public/tailwind.png';

// hooks
import { useEffect, useState } from 'react';

// applicaiton
export default function Home() {
  // functions
  const [darkmode, setdarkmode] = useState(false);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) {
    return null;
  }

  return (
    <div className={darkmode ? 'dark' : ''}>
      <Head>
        <title>Hello There 👋</title>
        <meta name="description" content="Generated by create next app" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-poppins bg-white px-10 md:px -20 lg:px-40 dark:bg-black">
        <section className="min-h-screen">
          <nav className="py-10 mb12 flex justify-between">
            <h1 className=" text-xl dark:text-white">Hello 👋</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li>
              {/* <li>
                <a
                  href="#"
                  className=" bg-purple-600 text-white px-4 py-2 boder-none rounded-md "
                >
                  Resume
                </a>
              </li> */}
            </ul>
          </nav>

          {/* hero */}
          <div className="text-center p-10 ">
            <h2 className=" text-5xl font-bold text-purple-700 md:text-6xl lg:text-7xl lg:mb-4">
              {/* Marcellino Putra Nugraha */}
              <Typewriter
                options={{
                  strings: [`Marcellino Putra Nugraha`],
                  autoStart: true,
                  loop: true,
                }}
              />
            </h2>
            <h3 className="text-2xl py-4 md:text-3xl dark:text-white">
              Fullstack Developer
            </h3>
            <p className=" text-sm py-2 text-gray-400 leading-6 md:text-md  max-w-xl mx-auto">
              Hello My name is Marcellino Putra Nugraha, I am a Fullstack
              Developer based in Indonesia. I've been a Fullstack Developer for
              more than 1 year. I have expertise in Javascript, Typescript,
              React, Next, Express js.
            </p>
          </div>
          {/* social media */}
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <a
              className="cursor: hover:cursor-pointer"
              href="https://github.com/marcellinoputra"
            >
              <AiFillGithub />
            </a>
            <a
              href="https://www.linkedin.com/in/marcellinoputra/"
              className="cursor: hover:cursor-pointer"
            >
              <AiFillLinkedin />
            </a>
          </div>
          {/* profile image */}
          <div
            className=" m-auto
           relative bg-gradient-to-b from-purple-200 w-80 p-5
            h-80 mt-20   rounded-full o"
          >
            <Image src={p2} alt="profile" layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* section 2 */}

        <section>
          <div>
            <h3 className=" text-3xl font-bold opacity-60 dark:text-white dark:opacity-100">
              Tech Stack
            </h3>
          </div>
          <div>
            <div className="md:grid lg:grid gap-10 mx-auto grid-cols-5">
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={tsIcon}
                  width={100}
                  height={100}
                  alt="Typescript Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white ">
                  Typescript
                </h3>
              </div>
              {/*  */}
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={reactIcon}
                  width={100}
                  height={100}
                  alt="React Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">React</h3>
              </div>
              {/*  */}
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={jsIcon}
                  width={100}
                  height={100}
                  alt="Javascript Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">
                  Javascript
                </h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={nextIcon}
                  width={100}
                  height={100}
                  alt="Nextjs Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">Next js</h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={expressIcon}
                  width={100}
                  height={100}
                  alt="Expressjs Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">
                  Express js
                </h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={cssIcon}
                  width={100}
                  height={100}
                  alt="CSS Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">CSS</h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={htmlIcon}
                  width={100}
                  height={100}
                  alt="Expressjs Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white">HTML</h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={prismaIcon}
                  width={75}
                  height={75}
                  alt="Expressjs Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white mt-2">
                  Prisma
                </h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={materialIcon}
                  width={100}
                  height={100}
                  alt="Expressjs Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white mt-5">
                  Material UI
                </h3>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
                <Image
                  src={tailwindIcon}
                  width={100}
                  height={100}
                  alt="Expressjs Icon"
                  className=" inline py-5"
                />
                <h3 className="text-2xl font-bold dark:text-white mt-10">
                  Tailwind
                </h3>
              </div>
            </div>
          </div>
        </section>

        {/* last section */}
        <section>
          <div>
            <h3 className=" text-3xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100">
              Working Experience
            </h3>
            <p className=" text-sm py-2 text-gray-400 leading-6">
              <ul>
                <li>
                  <p className="font-semibold">
                    1. Junior Mobile Developer at Kontrakin (Sep 2021 - Des
                    2021) (Assist Initial Developing of Kontrakin App){' '}
                    {`{Flutter}`}
                  </p>
                </li>
                <li>
                  <p className="font-semibold">
                    2. Fullstack Developer at Homefunding (Jan 2023 - now)
                    (Writing Code For Backend Core of Homefunding App, Backend
                    for Landing Page ,Dashboard, and Landing Page)
                    {`{React js, Next, Express, Prisma, Redis, Typescript, Strapi}`}
                  </p>
                </li>
                <p className="font-semibold">
                  3. Freelance at Gyloop (August 2023 - Nov 2023){' '}
                  {`{Typescript, Next, Express}`}
                </p>
              </ul>
            </p>
          </div>
          {/* Working Experience */}
        </section>
      </main>
    </div>
  );
}
